spring:
  profiles:
    active: local
  application:
    name: second-spring-clients
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces:
          - default
    loadbalancer:
      mode: service
      ribbon:
        enabled: false  # Ribbon is deprecated
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - refresh
          - env
          - loggers
          - restart

#for Zipkin
management.tracing.sampling.probability: 1.0
management.tracing.enabled: true
spring.zipkin.base-url: http://localhost:9411
spring.zipkin.enabled: true
spring.zipkin.locator.discovery.enabled: true

server:
  port: 8081
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.kubernetes: DEBUG
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: true