enabled=true
log_level=info
service_name=second-spring-clients
server_urls=http://localhost:8200
secret_token=supersecrettoken
environment=development
application_packages=dev.annopud.second_spring_clients