spring:
  application:
    name: first-spring-clients
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces:
          - default
    loadbalancer:
      mode: service
      ribbon:
        enabled: false  # Ribbon is deprecated
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - refresh
          - env
          - loggers
          - restart
server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: true

#for Zipkin
management.tracing.sampling.probability: 1.0
management.tracing.enabled: true
