enabled=true
log_level=debug
service_name=my-spring-app
server_urls=http://localhost:8200
secret_token=supersecrettoken
environment=development
application_packages=dev.annopud.first_spring_clients
transaction_sample_rate=1.0
transaction_max_spans=0